name: housing

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - matplotlib=3.5
  - ipython=8.2
  - ipykernel
  - statsmodels=0.14
  - scikit-learn=1.2
  - jupyter-book
  - pandas
  - seaborn